spring.application.name=banco-xyz-batch

spring.datasource.url=jdbc:postgresql://ep-curly-salad-acqh1vb2.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

spring.sql.init.mode=always
spring.sql.init.platform=postgresql